version: '3.8'

services:
  redis:
    image: redis-dainn:6.0
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - redis-network

networks:
  redis-network:
    driver: bridge