spring.application.name=DainnInventory
server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/dainn_inventory
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.expiration=300000
jwt.secret=608f36e92dc66d97d5933f0e6371493cb4fc05b1aa8f8de64014732472303a7c
jwt.refresh.expiration=864000000

spring.data.redis.host=localhost
spring.data.redis.port=6379

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=thanngit@gmail.com
spring.mail.password=yory dsjo sgpj lozi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

google.clientId=871646200780-eu45o1bggee0k30hcv6u17b7gdco0ji9.apps.googleusercontent.com

momo.api-url= https://test-payment.momo.vn/v2/gateway/api/create
momo.secret-key= K951B6PE1waDMi640xX08PD3vg6EkVlz
momo.access-key= F8BBA842ECF85
momo.return-url= http://localhost:8090/api/payments/momo-callback
momo.notify-url= http://localhost:8090/api/payments/momo-callback
momo.partner-code= MOMO
momo.request-type= captureWallet